import { join } from 'path';
import { existsSync, readFileSync, writeFileSync, renameSync } from 'fs';

const HEADER = '# Managed by penv — do not edit by hand. Generated by .preview/provision.sh';

export function envFilePath(root: string): string {
  return join(root, '.env.preview');
}

/** Parse KEY=VALUE pairs from text (heredoc / file body). Ignores blanks and #comments. */
export function parsePairs(text: string): Array<[string, string]> {
  const out: Array<[string, string]> = [];
  for (const raw of text.split('\n')) {
    const line = raw.trimEnd();
    const t = line.trim();
    if (!t || t.startsWith('#')) continue;
    const eq = t.indexOf('=');
    if (eq <= 0) continue;
    out.push([t.slice(0, eq).trim(), line.slice(line.indexOf('=') + 1)]);
  }
  return out;
}

/**
 * Atomically merge KEY=VALUE pairs into <root>/.env.preview.
 * Existing keys are overwritten in place; unknown keys are appended; comments
 * and unrelated lines are preserved. Write is temp-file + rename (atomic).
 */
export function mergeEnv(root: string, updates: Array<[string, string]>): string {
  const path = envFilePath(root);
  const existed = existsSync(path);
  const lines = existed ? readFileSync(path, 'utf8').split('\n') : [HEADER];
  // Drop trailing blank lines (from the file's trailing newline) so appended
  // keys don't get separated by a gap.
  while (lines.length && (lines[lines.length - 1] ?? '').trim() === '') lines.pop();

  const map = new Map(updates); // last value wins for dup keys
  const seen = new Set<string>();
  const result: string[] = [];

  for (const line of lines) {
    const t = line.trim();
    const eq = t.indexOf('=');
    if (!t || t.startsWith('#') || eq <= 0) {
      result.push(line);
      continue;
    }
    const key = t.slice(0, eq).trim();
    if (map.has(key)) {
      if (!seen.has(key)) {
        result.push(`${key}=${map.get(key)}`);
        seen.add(key);
      }
      // drop stale/duplicate occurrences
    } else {
      result.push(line);
    }
  }

  for (const [key, value] of updates) {
    if (!seen.has(key)) {
      result.push(`${key}=${value}`);
      seen.add(key);
    }
  }

  let text = result.join('\n') + '\n';
  if (!text.trim()) text = HEADER + '\n';

  const tmp = `${path}.tmp.${process.pid}`;
  writeFileSync(tmp, text);
  renameSync(tmp, path);
  return path;
}
